services:
  db:
    env_file:
      - .env
    image: timescale/timescaledb-ha:pg17
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: [ "-p", "${POSTGRES_PORT}", "-c", "ai.ollama_host=http://ollama:11434" ]
    expose:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  vectorizer_worker:
    image: timescale/pgai-vectorizer-worker:latest
    env_file:
      - .env
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      OLLAMA_HOST: http://ollama:11434
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy

  fastapi:
    env_file:
      - .env
    restart: always
    image: pgai-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - OLLAMA_HOST=http://ollama:11434
    stdin_open: true
    tty: true

  ollama:
    image: ollama/ollama:0.6.5
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD-SHELL", "ollama ps"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ollama_data:/root/.ollama

  ollama_model_puller:
    image: ollama/ollama:0.6.5
    env_file:
      - .env
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/bash","-c"]
    command: ["ollama pull ${OLLAMA_GENERATION_MODEL} && ollama pull ${OLLAMA_EMBEDDING_MODEL}"]
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data:
